def calc_pos_planet_rel_Earth(planet):
    
    '''Function to calculate the position of the planet with respect to Earth. 
    
    Parameters
    ---------------
    planet: object, object generated by Planet class

    Return
    ---------------
    planet: SkyCoord object
    '''

    if (type(planet.ra) != float) or (type(planet.dec) != float):
        return "Planet_label data type is incorrect!"
    
    #get the coordinates of the planet with respect to Earth using SkyCoord
    planet_obj = SkyCoord(ra=planet.ra*u.degree, dec=planet.dec*u.degree, frame='icrs')

    return planet_obj

def calc_pos_target_rel_Earth(target_label):

    '''Function to calculate the position of the target with respect to Earth. 
    
    Parameters
    ---------------
    target_label: str, name of the target
    
    Return
    ---------------
    target: SkyCoord object
    '''

    if type(target_label) != str:
        return "Target_label data type is incorrect!"
    
    #get the coordinates of the planet with respect to Earth using SkyCoord
    target = SkyCoord.from_name(target_label)

    return target


def calc_pos_target_rel_planet(planet, target_label):

    '''Function to calculate the position of the target with respect to the planet we are observing from. 
        
        Parameters
        ---------------
        planet: object, object generated by Planet class
        target_label: str, name of the target

        Return
        ---------------
        target_rel_planet: SkyCoord object
        '''
    
    #getting SkyCoord Info for target and planet
    planet = calc_pos_planet_rel_Earth(planet)
    target = calc_pos_target_rel_Earth(target_label)

    #transforming the target coordinates to be with respect to the planet
    target_rel_planet = target.transform_to(planet) 

    return target_rel_planet

        
